# SPDX-FileCopyrightText: © 2025 Peter Lemenkov
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["README.md", "LICENSE"]
SPDX-FileCopyrightText = "© 2025 Peter Lemenkov"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["scenarios.json", "wopr.mp4"]
SPDX-FileCopyrightText = "© 1983 MGM/UA Entertainment Co."
SPDX-License-Identifier = "LicenseRef-Fair-Use"
